### ISSUE TITLE
how to integrate the project in manual instead of cocoapods?

### ISSUE THREAD

**Issue by Dave1991** [rickytan/GPUUtilization#1]
For some reasons, my project can not use cocoapods. Therefore, I imported the files in the classes folder to my project. However, there are some compile errors, which are some symbols undefined, such as IOObjectRelease, IOIteratorNext. I wonder how to integrate the GPUUtilzation manually? Thanks:)

**Comment by rickytan** [comment]
add `other link flags`

**Comment by iphone-andy** [comment]
想问下other link flags要怎么设置，要引入IOKit么

**Comment by iphone-andy** [comment]
other link flags 加入 -framework 和 "IOKit"  ，感谢  @Dave1991
