### ISSUE TITLE
can't build in real machine 

### ISSUE THREAD

**Issue by oosnail** [rickytan/GPUUtilization#4]
The simulator can work success。
but can't build in real machine 

Showing Recent Messages
Undefined symbol: _IOServiceNameMatching
Undefined symbol: _IOIteratorNext
Undefined symbol: _IORegistryEntryGetChildIterator
Undefined symbol: _kIOMasterPortDefault
Undefined symbol: _IORegistryEntryCreateCFProperties
Undefined symbol: _IOServiceGetMatchingServices
Undefined symbol: _IOObjectRelease

**Comment by rickytan** [comment]
link with IOKit.framework. If you use Cocoapods, it will be done automatically. See #2 & #3

**Comment by oosnail** [comment]
> link with IOKit.framework. If you use Cocoapods, it will be done automatically. See #2 & #3

already solved ，thanks。
The simulator and the real machine must use different IOKit.frameworks
